### ISSUE TITLE
Resets menu layout when using with fancymenu.

### ISSUE THREAD

**Issue by frikinjay** [LimeAppleBoat/ThonkUtil#7]
When using a custom layout with fancymenu (2.6.2) and thonkutil (2.8.0-alpha.1+1.18). Switching menus brings back the vanilla buttons on the main menu back.

Also the branding in the bottom-left cant be hidden despite disabling it in the fancymenu settings.

**Comment by Keksuccino** [comment]
Hi, dev of [FancyMenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric) here!

Just wanted to add that this first happened after one of the last updates of ThonkUtil, it worked fine before.
The modifications ThonkUtil does to the main menu probably changed in the latest(?) update, which now breaks FancyMenu.

Would be great to have an option to disable main menu modifications, this would probably fix the issues!

Thank you :)

**Comment by Jab125** [comment]
> Hi, dev of [FancyMenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric) here!
> 
> Just wanted to add that this first happened after one of the last updates of ThonkUtil, it worked fine before. The modifications ThonkUtil does to the main menu probably changed in the latest(?) update, which now breaks FancyMenu.
> 
> Would be great to have an option to disable main menu modifications, this would probably fix the issues!
> 
> Thank you :)



> When using a custom layout with fancymenu (2.6.2) and thonkutil (2.8.0-alpha.1+1.18). Switching menus brings back the vanilla buttons on the main menu back.
> 
> Also the branding in the bottom-left cant be hidden despite disabling it in the fancymenu settings.

reason its an alpha, alphas break a lot of things (alpha is not production ready)

**Comment by Jab125** [comment]
will take a while to fix compatibility since using `Identifier` before mixins have loaded crashes all `IdentifierMixin`s as well as `TextMixin` and `TranslatableTextMixin`

**Comment by Jab125** [comment]
nvm found an easier solution

**Comment by Jab125** [comment]
<img width="613" alt="Screen Shot 2022-02-16 at 7 56 23 pm" src="https://user-images.githubusercontent.com/67534807/154229790-45aa0154-c127-4928-8caa-ff09de409509.png">
`if (!ThonkUtilTitleScreenConfig.MODIFY_TITLE_SCREEN.getValue()) return;` should fix it

**Comment by Jab125** [comment]
should be fixed in https://github.com/LimeAppleBoat/ThonkUtil/commit/13ad9a19f6757405f1610536e6cb94d97bbc4178, let me know if i screwed anything up

**Comment by Jab125** [comment]
@Keksuccino @frikinjay download 2.8.0-alpha.2 of curseforge, i turned the feature off by default, but you never know if something will get screwed up, so see if it's fixed.

**Comment by Keksuccino** [comment]
Hi! Thank you very much for the quick fix, the mentioned issues are all fixed as it seems!
But..now you've added a big red text that can't be removed ^^

![](https://cdn.discordapp.com/attachments/912100384410062848/943625053331931166/unknown.png)

I know, you want to tell people about the alpha state of the mod and that's okay, but please add a config or something, so users can turn this message off.

Thank you very much and have a great day!

//Edit: Btw: The reason why this is an issue in the alpha is that the alpha is used by many of your users already, because it seems like it mostly improves compatibility with other mods and since Goblin Traders now requires it too (as separate mod), a lot more people need to download it. Using older versions of Thonk mostly leads to other crashes with mods, that's why they use the alpha build ^^ Just wanted to clear this up a bit.

**Comment by Jab125** [comment]
@Keksuccino will be tackled when I'm out of school
